import { useState, type FormEvent } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { Button } from "../components/ui/button";
import { restaurant, whatsappUrl } from "../data/restaurant";

const reservationFields = [
  { key: "nome", label: "Nome", type: "text" },
  { key: "telefone", label: "Telefone", type: "tel" },
  { key: "pessoas", label: "Número de pessoas", type: "number" },
  { key: "data", label: "Data", type: "date" },
  { key: "hora", label: "Hora", type: "time" },
] as const;

export const Route = createFileRoute("/reservas")({ head: () => ({ meta: [{ title: "Reservar Mesa | Surf Café Nampula" }, { name: "description", content: "Prepare o seu pedido de reserva e envie-o diretamente ao Surf Café pelo WhatsApp." }, { property: "og:title", content: "Reservar Mesa | Surf Café Nampula" }, { property: "og:description", content: "Reserve uma mesa no Surf Café pelo WhatsApp." }, { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" }], links: [{ rel: "canonical", href: "/reservas" }] }), component: Reservas });
function Reservas(){const [form,setForm]=useState({nome:"",telefone:"",pessoas:"",data:"",hora:"",observacoes:""}); const update=(key:keyof typeof form,value:string)=>setForm({...form,[key]:value}); const submit=(e:FormEvent)=>{e.preventDefault(); const message=`Olá Surf Café! Gostaria de fazer uma reserva.\nNome: ${form.nome}\nTelefone: ${form.telefone}\nNúmero de pessoas: ${form.pessoas}\nData: ${form.data}\nHora: ${form.hora}\nObservações: ${form.observacoes || "Sem observações"}`; window.open(whatsappUrl(message),"_blank","noopener,noreferrer")}; return <div className="grid lg:grid-cols-2"><section className="bg-primary px-6 py-16 text-primary-foreground md:px-12 md:py-24 lg:min-h-[760px]"><p className="font-mono text-[10px] uppercase tracking-[0.3em] text-primary-foreground/50">Reservas</p><h1 className="mt-6 font-serif text-6xl font-extrabold italic leading-[0.9] md:text-8xl">Reserve a<br/>sua mesa</h1><p className="mt-8 max-w-md text-sm leading-7 text-primary-foreground/70">O pedido será enviado diretamente para o WhatsApp do Surf Café. A reserva fica sujeita a confirmação do restaurante.</p><div className="mt-12 border-t border-primary-foreground/20 pt-8 font-mono text-xs leading-7"><p>{restaurant.phone}</p>{restaurant.openingHours.map(x=><p key={x}>{x}</p>)}</div></section><form onSubmit={submit} className="grid content-start gap-6 px-6 py-16 md:px-12 md:py-24">{reservationFields.map(({key,label,type})=><label key={key} className="grid gap-2 font-mono text-[10px] uppercase tracking-[0.14em]">{label}<input required value={form[key]} onChange={e=>update(key,e.target.value)} type={type} min={key==="pessoas"?"1":undefined} className="h-12 border-b border-input bg-transparent px-1 font-sans text-base normal-case tracking-normal outline-none focus:border-primary"/></label>)}<label className="grid gap-2 font-mono text-[10px] uppercase tracking-[0.14em]">Observações<textarea value={form.observacoes} onChange={e=>update("observacoes",e.target.value)} rows={4} className="border border-input bg-transparent p-3 font-sans text-base normal-case tracking-normal outline-none focus:border-primary"/></label><Button type="submit" className="mt-2 h-14 rounded-none font-mono text-[10px] uppercase tracking-[0.16em]">Reservar pelo WhatsApp</Button></form></div>}